In [33]:
import torch
import numpy as np

In [34]:
v = torch.tensor([1, 2, 3, 4, 5, 6])
print(v)

tensor([1, 2, 3, 4, 5, 6])


In [35]:
print(v.dtype)

torch.int64


In [36]:
print(v[0])
print(v[1])
print(v[2])

tensor(1)
tensor(2)
tensor(3)


In [37]:
print(v[:])

tensor([1, 2, 3, 4, 5, 6])


In [38]:
print(v[1:4]) # stop index is exclusive

tensor([2, 3, 4])


In [39]:
print(v[1:])

tensor([2, 3, 4, 5, 6])


In [40]:
f = torch.FloatTensor([1, 2, 3, 4, 5, 6])
print(f)

tensor([1., 2., 3., 4., 5., 6.])


In [41]:
print(f.dtype)

torch.float32


In [42]:
print(f.size())

torch.Size([6])


In [43]:
v.view(6, 1) # reshape arrays like in numpy

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [44]:
# v.view(7, 1)
# will print an error

v.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [45]:
v.view(3, -1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [46]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [48]:
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [49]:
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)

[1 2 3 4 5]
