In [9]:
import torch

In [10]:
one_d = torch.arange(0, 9)
one_d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
two_d = one_d.view(3, 3) # 3 rows, 3 columns
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [13]:
two_d.dim()

2

In [14]:
two_d[0, 0] # first row and column

tensor(0)

In [15]:
two_d[1, 2]

tensor(5)

In [20]:
x = torch.arange(36).view(3, 3, 4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]]])

In [21]:
x.dim()

3